from django.contrib.sitemaps import Sitemap
from django.urls import reverse


class RzmrSitemap(Sitemap):
    # changefreq = 'never'
    priority = 1.0
    protocol = 'https'

    def items(self):
        items = [
            ('home', {}),
            ('about', {}),
            ('quality', {}),
            ('posts', {}),
            ('our-customer', {}),
            ('for-suppliers', {}),
            ('vacancies', {}),
            ('contacts', {}),
            ('spheres', {}),
            ('sphere', {'spheres_slug': 'mechanical_engineering'}),
            ('sphere', {'spheres_slug': 'aviation_industry'}),
            ('sphere', {'spheres_slug': 'gas_industry'}),
            ('sphere', {'spheres_slug': 'chemical_industry'}),
            ('sphere', {'spheres_slug': 'oil_refining'}),
            ('sphere', {'spheres_slug': 'food_industry'}),
            ('metalhoses', {}),
            ('metalhoses-fittings', {}),
            ('metalhoses-corrugations', {}),
            ('metalhoses-corrugation', {'metalhoses_corrugation_slug': 'standartnaya'}),
            ('metalhoses-corrugation', {'metalhoses_corrugation_slug': 'povishennoy_gibkosti'}),
            ('metalhoses-corrugation', {'metalhoses_corrugation_slug': 'tyazhelaya_seriya'}),
            ('metalhoses-corrugation', {'metalhoses_corrugation_slug': 'spiralnaya'}),
            ('metalhoses-corrugation', {'metalhoses_corrugation_slug': 'dvukhsloynaya'}),
            ('metalhoses-braids', {}),
            ('metalhoses-braid', {'metalhoses_braid_slug': 'odnosloynaya'}),
            ('metalhoses-braid', {'metalhoses_braid_slug': 'dvukhsloynaya'}),
            ('metalhoses-braid', {'metalhoses_braid_slug': 'trekhsloynaya'}),
            ('metalhoses-inners', {}),
            ('metalhoses-inner', {'metalhoses_inner_slug': 'trubnyy'}),
            ('metalhoses-inner', {'metalhoses_inner_slug': 'valtsovannyy'}),
            ('metalhoses-inner', {'metalhoses_inner_slug': 'opletochnyy'}),
            ('metalhoses-inner', {'metalhoses_inner_slug': 'ptfe'}),
            ('metalhoses-outsides', {}),
            ('metalhoses-outside', {'metalhoses_outside_slug': 'termochekhol'}),
            ('metalhoses-outside', {'metalhoses_outside_slug': 'termorukav'}),
            ('metalhoses-outside', {'metalhoses_outside_slug': 'rezinovaya_obolochka'}),
            ('metalhoses-outside', {'metalhoses_outside_slug': 'pruzhina'}),
            ('metalhoses-outside', {'metalhoses_outside_slug': 'pletenka_mednaya_luzhenaya_pml'}),
            ('metalhoses-special', {}),
            ('metalhoses-recommendations', {}),
            ('metalhoses-installation', {}),
            ('metalhoses-standarts-rgm', {}),
            ('metalhoses-hpress-rgm', {}),
            ('metalhoses-for-welding', {}),
            ('metalhoses-rgm', {}),
            ('metalhoses-v-opletke', {}),
            ('gibkie-truboprovody', {}),
            ('ptfe-hoses', {}),
            ('ptfe-gofrirovanniy', {}),
            ('ptfe-recommendations', {}),
            ('ptfe-installation', {}),
            ('ptfe-fittings', {}),
            ('ptfe-standarts', {}),
            ('ptfe-hpress', {}),
            ('ptfe-pipes', {}),
            ('ptfe-pipe', {'ptfe_pipe_slug': 'ploskaya_standartnoe_ispolnenie'}),
            ('ptfe-pipe', {'ptfe_pipe_slug': 'ploskaya_tolstostennaya'}),
            ('ptfe-pipe', {'ptfe_pipe_slug': 'gofrirovannaya_standartnoe_ispolnenie'}),
            ('ptfe-pipe', {'ptfe_pipe_slug': 'gofrirovannaya_tolstostennaya'}),
            ('ptfe-braids', {}),
            ('ptfe-braid', {'ptfe_braid_slug': 'odnosloynaya'}),
            ('ptfe-braid', {'ptfe_braid_slug': 'dvukhsloynaya'}),
            ('ptfe-braid', {'ptfe_braid_slug': 'trekhsloynaya'}),
            ('ptfe-liners', {}),
            ('ptfe-liner', {'ptfe_liner_slug': 'gofrirovannoy_trubki_na_flanets'}),
            ('ptfe-liner', {'ptfe_liner_slug': 'ploskoy_trubki_na_flanets'}),
            ('ptfe-liner', {'ptfe_liner_slug': 'ploskoy_trubki_na_nippel_gayki'}),
            ('ptfe-inners', {}),
            ('ptfe-inner', {'ptfe_inner_slug': 'antistaticheskaya_prisadka_ploskaya'}),
            ('ptfe-inner', {'ptfe_inner_slug': 'antistaticheskaya_prisadka_gofrirovannaya'}),
            ('ptfe-outsides', {}),
            ('ptfe-outside', {'ptfe_outside_slug': 'termochekhol'}),
            ('ptfe-outside', {'ptfe_outside_slug': 'rezinovaya_obolochka'}),
            ('ptfe-outside', {'ptfe_outside_slug': 'pruzhina'}),
            ('ptfe-outside', {'ptfe_outside_slug': 'ploskaya_trubka_v_metallorukave_v_opletke'}),
            ('ptfe-outside', {'ptfe_outside_slug': 'gofrirovannaya_trubka_v_metallorukave_v_opletke'}),
            ('engineering', {}),
            ('engineering-accessories', {}),
            ('engineering-test', {}),
            ('workspace-filters', {}),
            ('composite', {}),
            ('composite', {'composite_slug': 'EGE'}),
            ('composite', {'composite_slug': 'SSE'}),
            ('composite', {'composite_slug': 'SST'}),
            ('composite', {'composite_slug': 'SGT'}),
            ('composite', {'composite_slug': 'SGE'}),
            ('composite', {'composite_slug': 'GGE'}),
            ('composite', {'composite_slug': 'AAE'}),
            ('fittings', {}),
            ('fitting', {'fitting_slug': 'gayka-nakidnaya-pod-tortsevoe-uplotnenie'}),
            ('fitting', {'fitting_slug': 'mufta-amerikanka-bp-bp'}),
            ('fitting', {'fitting_slug': 'mufta-amerikanka-s-vnutrenney-rezboy-hp-bp'}),
            ('fitting', {'fitting_slug': 'mufta-amerikanka-s-naruzhnoy-rezboy-hp-hp'}),
            ('fitting', {'fitting_slug': 'nakidnaya-gayka-s-nippelem-konus-s-uglom-74'}),
            ('fitting', {'fitting_slug': 'nakidnaya-gayka-s-nippelem-konus-s-uglom-24'}),
            ('fitting', {'fitting_slug': 'nakidnaya-gayka-s-nippelem-sfera-pod-konus-s-uglom-60'}),
            ('fitting', {'fitting_slug': 'perekhodnik-gayka-gayka'}),
            ('fitting', {'fitting_slug': 'perekhodnik-gayka-shtutser'}),
            ('fitting', {'fitting_slug': 'perekhodnik-shtutser-shtutser'}),
            ('fitting', {'fitting_slug': 'fitting-dk0'}),
            ('fitting', {'fitting_slug': 'fitting-dk-shtutser'}),
            ('fitting', {'fitting_slug': 'fitting-dki'}),
            ('fitting', {'fitting_slug': 'fitting-dkol'}),
            ('fitting', {'fitting_slug': 'shtutser-s-vnutrenney-rezboy'}),
            ('fitting', {'fitting_slug': 'shtutser-s-naruzhnoy-rezboy'}),
            ('flanges', {}),
            ('flange', {'flange_slug': 'flantsevoe-soedinenie-gost-12821-80'}),
            ('flange', {'flange_slug': 'flantsevoe-soedinenie-gost-12822-80'}),
            ('flange', {'flange_slug': 'flantsevoe-soedinenie-s-otkidnymi-boltami'}),
            ('flange', {'flange_slug': 'flantsevoe-soedinenie-svobodnoe-na-otbortovke'}),
            ('flange', {'flange_slug': 'flantsevoe-soedinenie-tip-01-po-gost-33259-2015'}),
            ('flange', {'flange_slug': 'flantsy-iz-nalichiya'}),
            ('quick-release-coupling', {}),
            ('quick-release-coupling', {'coupling_slug': 'adaptor-bystrorazyemnogo-soedineniya-tipa-kamlok-mufta'}),
            ('quick-release-coupling', {'coupling_slug': 'adaptor-bystrorazyemnogo-soedineniya-tipa-kamlok-shtutser'}),
            ('quick-release-coupling', {'coupling_slug': 'armatura-pmt'}),
            ('quick-release-coupling', {'coupling_slug': 'gayka-rot-isp-1'}),
            ('quick-release-coupling', {'coupling_slug': 'gayka-rot-isp-2'}),
            ('quick-release-coupling', {'coupling_slug': 'gayka-rot-isp-3'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-a'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-b'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-d0'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-dc'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-dp'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-e'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-c'}),
            ('quick-release-coupling', {'coupling_slug': 'kamlok-tipa-f'}),
            ('quick-release-coupling', {'coupling_slug': 'koltso-uplotnitelnoe-dlya-gayki-rot'}),
            ('quick-release-coupling', {'coupling_slug': 'strubtsina-s-prizhimnym-ustroystvom-sug'}),
        ]
        return items

    def location(self, item):
        url, kwargs = item
        return reverse(url, kwargs=kwargs)
