from django.urls import path
from rzmr.views import *

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('about/quality/', QualityView.as_view(), name='quality'),
    path('about/our-customer/', OurCustomerView.as_view(), name='our-customer'),
    path('about/for-suppliers/', ForSuppliersView.as_view(), name='for-suppliers'),
    path('about/vacancies/', VacanciesView.as_view(), name='vacancies'),
    path('about/contacts/', ContactsView.as_view(), name='contacts'),
    path('metalhoses/', MetalhosesView.as_view(), name='metalhoses'),
    path('metalhoses/fittings/', MetalhosesFittingsView.as_view(),
         name='metalhoses-fittings'),
    path('metalhoses/corrugation/', CorrugationView.as_view(),
         name='metalhoses-corrugation'),
    path('metalhoses/corrugation/standartnaya/', CorrugationStandartnayaView.as_view(),
         name='metalhoses-corrugation-standartnaya'),
    path('metalhoses/corrugation/povishennoy-gibkosti/', CorrugationPovyshennoyGibkostiView.as_view(),
         name='metalhoses-corrugation-povishennoy_gibkosti'),
    path('metalhoses/corrugation/tyazhelaya-seriya/', CorrugationTyazhelayaSeriyaView.as_view(),
         name='metalhoses-corrugation-tyazhelaya_seriya'),
    path('metalhoses/corrugation/spiralnaya/', CorrugationSpiralnayaView.as_view(),
         name='metalhoses-corrugation-spiralnaya'),
    path('metalhoses/corrugation/dvukhsloynaya/', CorrugationDvuhsloinayaView.as_view(),
         name='metalhoses-corrugation-dvukhsloynaya'),
    path('metalhoses/braid/', BraidView.as_view(), name='metalhoses-braid'),
    path('metalhoses/braid/odnosloynaya/', BraidOdnosloynayaView.as_view(),
         name='metalhoses-braid-odnosloynaya'),
    path('metalhoses/braid/dvukhsloynaya/', BraidDvukhsloynayaView.as_view(),
         name='metalhoses-braid-dvukhsloynaya'),
    path('metalhoses/braid/trekhsloynaya/', BraidTrekhsloynayaView.as_view(),
         name='metalhoses-braid-trekhsloynaya'),
    path('metalhoses/inner/', InnerView.as_view(), name='metalhoses-inner'),
    path('metalhoses/inner/trubnyy/', InnerTrubnyyView.as_view(),
         name='metalhoses-inner-trubnyy'),
    path('metalhoses/inner/valtsovannyy/', InnerValtsovannyyView.as_view(),
         name='metalhoses-inner-valtsovannyy'),
    path('metalhoses/inner/opletochnyy/', InnerOpletochnyyView.as_view(),
         name='metalhoses-inner-opletochnyy'),
    path('metalhoses/inner/ptfe/', InnerPTFEView.as_view(),
         name='metalhoses-inner-ptfe'),
    path('metalhoses/outside/', OutsideView.as_view(), name='metalhoses-outside'),
    path('metalhoses/outside/termochekhol/', OutsideTermochekholView.as_view(),
         name='metalhoses-outside-termochekhol'),
    path('metalhoses/outside/termorukav/', OutsideTermorukavView.as_view(),
         name='metalhoses-outside-termorukav'),
    path('metalhoses/outside/rezinovaya-obolochka/', OutsideRezinovayaObolochkaView.as_view(),
         name='metalhoses-outside-rezinovaya_obolochka'),
    path('metalhoses/outside/pruzhina/', OutsidePruzhinaView.as_view(),
         name='metalhoses-outside-pruzhina'),
    path('metalhoses/outside/pletenka-mednaya-luzhenaya-pml/', OutsidePletenkaMednayaLuzhenayaPmlView.as_view(),
         name='metalhoses-outside-pletenka_mednaya_luzhenaya_pml'),
    path('metalhoses/recommendations/', MetalhosesRecommendationsView.as_view(),
         name='metalhoses-recommendations'),
    path('metalhoses/installation/', InstallationSafetyView.as_view(),
         name='metalhoses-installation'),
    path('metalhoses/standarts/', StandartsRGMView.as_view(),
         name='metalhoses-standarts-grm'),
    path('ptfe/', PTFEView.as_view(), name='ptfe'),
    path('ptfe/recommendations/', PTFERecommendationsView.as_view(),
         name='ptfe-recommendations'),
    path('ptfe/fittings/', PTFEFittingsView.as_view(), name='ptfe-fittings'),
    path('ptfe/standarts/', PTFEStandartsView.as_view(), name='ptfe-standarts'),
    path('ptfe/pipe/', PTFEPipeView.as_view(), name='ptfe-pipe'),
    path('ptfe/pipe/ploskaya-standartnoe-ispolnenie/', PTFEPloskayaStandartnoeIspolnenieView.as_view(),
         name='ptfe-ploskaya-standartnoe-ispolnenie'),
    path('ptfe/pipe/ploskaya-tolstostennaya/', PTFEPloskayaTolstostennayaView.as_view(),
         name='ptfe-ploskaya-tolstostennaya'),
    path('ptfe/pipe/gofrirovannaya-standartnoe-ispolnenie/', PTFEGofrirovannayaStandartnoeIspolnenieView.as_view(),
         name='ptfe-gofrirovannaya-standartnoe-ispolnenie'),
    path('ptfe/pipe/gofrirovannaya-tolstostennaya/', PTFEGofrirovannayaTolstostennayaView.as_view(),
         name='ptfe-gofrirovannaya-tolstostennaya'),
    path('ptfe/liner/', PTFELinerView.as_view(), name='ptfe-liner'),
    path('ptfe/liner/ptfe-futerovka-ploskoy-trubki-na-flanets/', PTFEFuterovkaPloskoyTrubkiNaFlanetsView.as_view(),
         name='ptfe-futerovka-ploskoy-trubki-na-flanets'),
    path('ptfe/liner/ptfe-futerovka-gofrirovannoy-trubki-na-flanets/', PTFEFuterovkaGofrirovannoyTrubkiNaFlanetsView.as_view(),
         name='ptfe-futerovka-gofrirovannoy-trubki-na-flanets'),
    path('ptfe/liner/ptfe-futerovka-ploskoy-trubki-na-nippel-gayki/', PTFEFuterovkaPloskoyTrubkiNaNippelGaykiView.as_view(),
         name='ptfe-futerovka-ploskoy-trubki-na-nippel-gayki'),

    path('engineering/', EngineeringView.as_view(), name='engineering'),
    path('engineering/accessories/', EngineeringAccessoriesView.as_view(),
         name='engineering-accessories'),
    path('engineering/test/', EngineeringTestView.as_view(),
         name='engineering-test'),
    path('privacy/', PrivacyView.as_view(), name='privacy'),
]
