from django.urls import path
from rzmr.views import *

urlpatterns = [
     path('', IndexView.as_view(), name='home'),
     path('robots.txt/', RobotView.as_view()),
     path('request-phone-call/', RequestPhoneCall.as_view(), name='request-phone-call'),
     path('about/', AboutView.as_view(), name='about'),
     path('about/quality/', QualityView.as_view(), name='quality'),
     path('about/our-customer/', OurCustomerView.as_view(), name='our-customer'),
     path('about/for-suppliers/', ForSuppliersView.as_view(), name='for-suppliers'),
     path('about/vacancies/', VacanciesView.as_view(), name='vacancies'),
     path('about/contacts/', ContactsView.as_view(), name='contacts'),
     path('metalhoses/', MetalhosesView.as_view(), name='metalhoses'),
     path('metalhoses/fittings/', MetalhosesFittingsView.as_view(),
          name='metalhoses-fittings'),
     path('metalhoses/corrugation/', MetalhosesCorrugationView.as_view(),
          name='metalhoses-corrugation'),
     path('metalhoses/corrugation/standartnaya/', MetalhosesCorrugationStandartnayaView.as_view(),
          name='metalhoses-corrugation-standartnaya'),
     path('metalhoses/corrugation/povishennoy-gibkosti/', MetalhosesCorrugationPovyshennoyGibkostiView.as_view(),
          name='metalhoses-corrugation-povishennoy_gibkosti'),
     path('metalhoses/corrugation/tyazhelaya-seriya/', MetalhosesCorrugationTyazhelayaSeriyaView.as_view(),
          name='metalhoses-corrugation-tyazhelaya_seriya'),
     path('metalhoses/corrugation/spiralnaya/', MetalhosesCorrugationSpiralnayaView.as_view(),
          name='metalhoses-corrugation-spiralnaya'),
     path('metalhoses/corrugation/dvukhsloynaya/', MetalhosesCorrugationDvuhsloinayaView.as_view(),
          name='metalhoses-corrugation-dvukhsloynaya'),
     path('metalhoses/braid/', MetalhosesBraidView.as_view(),
          name='metalhoses-braid'),
     path('metalhoses/braid/odnosloynaya/', MetalhosesBraidOdnosloynayaView.as_view(),
          name='metalhoses-braid-odnosloynaya'),
     path('metalhoses/braid/dvukhsloynaya/', MetalhosesBraidDvukhsloynayaView.as_view(),
          name='metalhoses-braid-dvukhsloynaya'),
     path('metalhoses/braid/trekhsloynaya/', MetalhosesBraidTrekhsloynayaView.as_view(),
          name='metalhoses-braid-trekhsloynaya'),
     path('metalhoses/inner/', MetalhosesInnerView.as_view(),
          name='metalhoses-inner'),
     path('metalhoses/inner/trubnyy/', MetalhosesInnerTrubnyyView.as_view(),
          name='metalhoses-inner-trubnyy'),
     path('metalhoses/inner/valtsovannyy/', MetalhosesInnerValtsovannyyView.as_view(),
          name='metalhoses-inner-valtsovannyy'),
     path('metalhoses/inner/opletochnyy/', MetalhosesInnerOpletochnyyView.as_view(),
          name='metalhoses-inner-opletochnyy'),
     path('metalhoses/inner/ptfe/', MetalhosesInnerPTFEView.as_view(),
          name='metalhoses-inner-ptfe'),
     path('metalhoses/outside/', MetalhosesOutsideView.as_view(),
          name='metalhoses-outside'),
     path('metalhoses/outside/termochekhol/', MetalhosesOutsideTermochekholView.as_view(),
          name='metalhoses-outside-termochekhol'),
     path('metalhoses/outside/termorukav/', MetalhosesOutsideTermorukavView.as_view(),
          name='metalhoses-outside-termorukav'),
     path('metalhoses/outside/rezinovaya-obolochka/', MetalhosesOutsideRezinovayaObolochkaView.as_view(),
          name='metalhoses-outside-rezinovaya_obolochka'),
     path('metalhoses/outside/pruzhina/', MetalhosesOutsidePruzhinaView.as_view(),
          name='metalhoses-outside-pruzhina'),
     path('metalhoses/outside/pletenka-mednaya-luzhenaya-pml/', MetalhosesOutsidePletenkaMednayaLuzhenayaPmlView.as_view(),
          name='metalhoses-outside-pletenka_mednaya_luzhenaya_pml'),
     path('metalhoses/recommendations/', MetalhosesRecommendationsView.as_view(),
          name='metalhoses-recommendations'),
     path('metalhoses/installation/', MetalhosesInstallationSafetyView.as_view(),
          name='metalhoses-installation'),
     path('metalhoses/standarts/', StandartsRGMView.as_view(),
          name='metalhoses-standarts-grm'),
     path('ptfe/', PTFEhosesView.as_view(), name='ptfe-hoses'),
     path('ptfe/recommendations/', PTFERecommendationsView.as_view(),
          name='ptfe-recommendations'),
     path('ptfe/installation/', PTFEInstallationSafetyView.as_view(),
          name='ptfe-installation'),
     path('ptfe/fittings/', PTFEFittingsView.as_view(), name='ptfe-fittings'),
     path('ptfe/standarts/', PTFEStandartsView.as_view(), name='ptfe-standarts'),
     path('ptfe/pipe/', PTFEPipesView.as_view(), name='ptfe-pipes'),
     path('ptfe/pipe/<slug:ptfe_pipe_slug>/', PTFEPipeView.as_view(), name='ptfe-pipe'),
     path('ptfe/liner/', PTFELinersView.as_view(), name='ptfe-liners'),
     path('ptfe/liner/<slug:ptfe_liner_slug>/', PTFELinerView.as_view(), name='ptfe-liner'),
     path('ptfe/inner/', PTFEInnersView.as_view(), name='ptfe-inners'),
     path('ptfe/inner/<slug:ptfe_inner_slug>/', PTFEInnerView.as_view(), name='ptfe-inner'),
     path('ptfe/outside/', PTFEOutsidesView.as_view(), name='ptfe-outsides'),
     path('ptfe/outside/<slug:ptfe_outside_slug>/', PTFEOutsideView.as_view(), name='ptfe-outside'),
     path('engineering/', EngineeringView.as_view(), name='engineering'),
     path('engineering/accessories/', EngineeringAccessoriesView.as_view(),
          name='engineering-accessories'),
     path('engineering/test/', EngineeringTestView.as_view(),
          name='engineering-test'),
     path('privacy/', PrivacyView.as_view(), name='privacy'),
     path('filters/workspace-filters/', WorkspaceFiltersView.as_view(), name='workspace-filters'),
     path('composite/', CompositesView.as_view(), name='composite'),
     path('composite/<slug:composite_slug>/', CompositeView.as_view(), name='composite'),
     path('fittings/', FittingsView.as_view(), name='fittings'),
     path('fittings/<slug:fitting_slug>/', FittingView.as_view(), name='fitting'),
     path('flanges/', FlangesView.as_view(), name='flanges'),
     path('flange/<slug:flange_slug>/', FlangeView.as_view(), name='flange'),
     path('quick-release-coupling/', QuickReleaseCouplingsView.as_view(), name='quick-release-coupling'),
     path('quick-release-coupling/<slug:coupling_slug>/', QuickReleaseCouplingView.as_view(), name='quick-release-coupling'),
]
